name: Push File & Security Scans

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "eng21ct0039@dsu.edu.in"
          git config --global user.name "Sukriti"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: |
          pip install bandit
          bandit -r .

  copy-file:
    runs-on: ubuntu-latest
    needs: [bandit_scan]
    permissions:
      contents: write
      packages: write
      pages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: readme.md
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'readme.md'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'

      - name: r.bat
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'r.bat'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'

      - name: pnpm-workspace.yaml
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'pnpm-workspace.yaml'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'
          
      - name: pnpm-lock.yaml
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: 'pnpm-lock.yaml'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti' 
          
      - name: frontend
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: '/frontend'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'

      - name: backend
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TOKEN }} # Use the correct environment variable name
        with:
          source_file: '/backend'
          destination_repo: 'LSM-E-Copyright/Test'
          user_email: 'eng21ct0039@dsu.edu.in'
          user_name: 's-sukriti'
